name: Test
on:
  repository_dispatch:
    types: [test-command]

jobs:
  parse-args:
    outputs:
      use-pr-artifacts: ${{ steps.set-output.outputs.use-pr-artifacts}}
    runs-on: ubuntu-latest
    steps:
      - name: set vars
        run: echo "use-pr-artifacts=${{ github.event.client_payload.slash_command.args.named.update-services || github.event.client_payload.slash_command.args.unnamed.arg2 == 'changes' }}" >> $GITHUB_ENV
      - name: set output
        id: set-output
        run: echo "use-pr-artifacts=${{ env.use-pr-artifacts }}" >> $GITHUB_OUTPUT
      - name: show output
        run: echo "use-pr-artifacts=${{ steps.set-output.outputs.use-pr-artifacts }}"

  show-args:
    needs: [parse-args]
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: echo "env.use-pr-artifacts=${{ env.use-pr-artifacts }}"
      - name: echo output
        run: echo "parse-args.output.use-pr-artifacts=${{ needs.parse-args.outputs.use-pr-artifacts }}"
